### ISSUE TITLE
Status on UI styling

### ISSUE THREAD

**Issue by RMCS5800** [Ultimates1/employee-management-system#30]
Completed UI for Login, Reset request, Reset Password.
Will now proceed into Home Manager, Home Employee, Profile
Need to discuss with Mi about Budget, Evaluation, Document page(s)

**Comment by RMCS5800** [comment]
Have thus far(11.25) completed all the following UI styling:Login, Reset Request, Reset Pass, Home Manager, Home Employee, Management.
Yet to complete 
1)Profile  
2) Timekeeping 
3) Leave request

**Comment by yamiryu** [comment]
Per discussion, we will remove Evaluation page. Budget is waiting to see if time-permitted.

**Comment by yamiryu** [comment]
Done
