### ISSUE TITLE
Authenticate users

### ISSUE THREAD

**Issue by yamiryu** [Ultimates1/employee-management-system#4]
- Collect data from inputs (user and password)
- Authenticate with AccessController
- Reject message if failed
- Login to appropriate contents in homepage (populate homepage tiles with results received from AccessController)

**Comment by yamiryu** [comment]
Some basic connection is done in cfbb3d91719dfcaf81d8d40797027da2d31a51ef

**Comment by RMCS5800** [comment]
Week October 28,
1. Make Forgot ID Password route page
2.Route pages correctly with login

**Comment by RMCS5800** [comment]
Week October 28:
1.Make Forgot ID Password route page
2.Route pages correctly with logi

**Comment by yamiryu** [comment]
Done
