### ISSUE TITLE
Route to pages correctly with login

### ISSUE THREAD

**Issue by yamiryu** [Ultimates1/employee-management-system#5]
- Once logged in, should be able to go any pages
- Once logged out, going to any pages will redirect to login page

**Comment by RMCS5800** [comment]
Right now we only have the sign in
We need to have other pages set up to have the login page;hence, this should be last.

**Comment by yamiryu** [comment]
Done by having a saved state of logged in/out. Before loading any pages other than log in, forgot, reset, do a check, and reroute to log in page if not logged in
