### ISSUE TITLE
Functions for Workflow page

### ISSUE THREAD

**Issue by yamiryu** [Ultimates1/employee-management-system#51]
- getWorkflows(userID): Get workflow list using userID, probably same list as leaveRequest, but with extra employeeID/name field(s)

http://localhost:8080/ems/workflow/getpending/{user}

{
    "pendinglist": [
        {
            "workflowId": 11,
            "createDate": "2018-12-02T19:15:47.172+0000",
            "updateDate": null,
            "userId": 1,
            "leaveRequestId": 6,
            "status": "P",
            "comment": null
        },
        {
            "workflowId": 13,
            "createDate": "2018-12-02T19:17:02.865+0000",
            "updateDate": null,
            "userId": 1,
            "leaveRequestId": 7,
            "status": "P",
            "comment": null
        }
    ],
    "success": true,
    "message": "Retrieved workflow request successfully."
}

-Action on pending request

http://localhost:8080/ems/workflow/action/{user}?workflowid=11&action=A&comment=Okay

{
    "success": true,
    "message": "Workflow request updated successfully."
}

**Comment by nambvp03** [comment]
Updated issue, added url and response.

**Comment by yamiryu** [comment]
Done

**Comment by yamiryu** [comment]
Done
