### ISSUE TITLE
Document generation function

### ISSUE THREAD

**Issue by nambvp03** [Ultimates1/employee-management-system#9]
- Any module call this function with HTTP Post request. In the body part, it will pass content and formatting of document, path to store, employee related to document.

- Generate pdf based on request, and store it to dedicated path.

- Send document to related employee.

**Comment by dvthumar** [comment]
public static void main(String[] args)
    	throws DocumentException, IOException {
    	new HelloWorld().createPdf(RESULT);

public void createPdf(String filename)
	throws DocumentException, IOException {
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(filename));
        document.open();
        document.add(new Paragraph("Hello World!"));
        document.close();
    }

**Comment by yamiryu** [comment]
Done, but not connected front end
